viruses:
  - sarscov2

sarscov2:
  # prepare sequence count data
  s3_metadata: s3://nextstrain-ncov-private/metadata.tsv.zst
  subset_columns:
    - strain
    - date
    - country
    - clade_nextstrain
    - QC_overall_status
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-04-01"
  max_date: "2024-09-01"
  location_min_seq: 50
  clade_min_seq: 2000
  # run MLR estimates
  pivot: "20A"

mlr_config: "defaults/mlr-config.yaml"
