datasets:
  - 7PET_clades

# V.c. 

7PET_clades:
  local_metadata: "data/7PET_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade
    --location-column country
  min_date: "1960-01-01"
  max_date: "2024-01-01"
  clade_min_seq: 100
  pivot: "12"
  generation_time: 2.0

mlr_config: "defaults/mlr-config.yaml"
