datasets:
  - sarscov2_2020
  - sarscov2_2020-21
  - sarscov2_2021
  - sarscov2_2021-22
  - sarscov2_2022
  - sarscov2_2022-23
  - sarscov2_2023
  - sarscov2_2023-24
  - sarscov2_2024
  - h3n2_2016-17
  - h3n2_2017-18
  - h3n2_2018-19
  - h3n2_2019-20
  - h3n2_2020-21
  - h3n2_2021-22
  - h3n2_2022-23
  - h3n2_2023-24

# H3N2 uses a 2-year analysis window and slides 1-year forward

h3n2_2016-17:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2016-01-01"
  max_date: "2017-12-31"
  clade_min_seq: 100
  pivot: "B.1"
  generation_time: 3.2 

h3n2_2017-18:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2017-01-01"
  max_date: "2018-12-31"
  clade_min_seq: 100
  pivot: "B.2"
  generation_time: 3.2

h3n2_2018-19:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2018-01-01"
  max_date: "2019-12-31"
  clade_min_seq: 100
  pivot: "C.1"
  generation_time: 3.2

h3n2_2019-20:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2019-01-01"
  max_date: "2020-12-31"
  clade_min_seq: 100
  pivot: "E.2"
  generation_time: 3.2

h3n2_2020-21:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2020-01-01"
  max_date: "2021-12-31"
  clade_min_seq: 50
  pivot: "G.1.1.1"
  generation_time: 3.2

h3n2_2021-22:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2021-01-01"
  max_date: "2022-12-31"
  clade_min_seq: 50
  pivot: "G.1.1.1"
  generation_time: 3.2

h3n2_2022-23:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2022-01-01"
  max_date: "2023-12-31"
  clade_min_seq: 100
  pivot: "G.2"
  generation_time: 3.2

h3n2_2023-24:
  local_metadata: "data/h3n2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column subclade
    --filter-columns country
    --filter-query "country == 'USA'"
  min_date: "2023-01-01"
  max_date: "2024-12-31"
  clade_min_seq: 100
  pivot: "J.2"
  generation_time: 3.2

sarscov2_2020:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-01-01"
  max_date: "2020-12-31"
  clade_min_seq: 3000
  pivot: "19B"
  generation_time: 3.2

sarscov2_2020:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-01-01"
  max_date: "2020-12-31"
  clade_min_seq: 3000
  pivot: "19B"
  generation_time: 3.2

sarscov2_2020-21:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-07-01"
  max_date: "2021-06-30"
  clade_min_seq: 3000
  pivot: "20G"
  generation_time: 3.2

sarscov2_2021:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2021-01-01"
  max_date: "2021-12-31"
  clade_min_seq: 3000
  pivot: "21J"
  generation_time: 3.2

sarscov2_2021-22:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2021-07-01"
  max_date: "2022-06-30"
  clade_min_seq: 3000
  pivot: "21K"
  generation_time: 3.2

sarscov2_2022:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2022-01-01"
  max_date: "2022-12-31"
  clade_min_seq: 3000
  pivot: "22B"
  generation_time: 3.2

sarscov2_2022-23:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2022-07-01"
  max_date: "2023-06-30"
  clade_min_seq: 3000
  pivot: "22E"
  generation_time: 3.2

sarscov2_2023:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2023-01-01"
  max_date: "2023-12-31"
  clade_min_seq: 3000
  pivot: "23B"
  generation_time: 3.2

sarscov2_2023-24:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2023-07-01"
  max_date: "2024-06-30"
  clade_min_seq: 3000
  pivot: "24A"
  generation_time: 3.2

sarscov2_2024:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2024-01-01"
  max_date: "2024-12-31"
  clade_min_seq: 3000
  pivot: "24A"
  generation_time: 3.2

mlr_config: "defaults/mlr-config.yaml"
