datasets:
  - sarscov2_2020
  - sarscov2_2020-21
  - sarscov2_2021
  - sarscov2_2021-22
  - sarscov2_2022
  - sarscov2_2022-23
  - sarscov2_2023
  - sarscov2_2023-24
  - sarscov2_2024

sarscov2_2020:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-01-01"
  max_date: "2020-12-31"
  clade_min_seq: 3000
  pivot: "19B"

sarscov2_2020-21:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2020-07-01"
  max_date: "2021-06-30"
  clade_min_seq: 3000
  pivot: "20G"

sarscov2_2021:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2021-01-01"
  max_date: "2021-12-31"
  clade_min_seq: 3000
  pivot: "21J"

sarscov2_2021-22:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2021-07-01"
  max_date: "2022-06-30"
  clade_min_seq: 3000
  pivot: "21K"

sarscov2_2022:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2022-01-01"
  max_date: "2022-12-31"
  clade_min_seq: 3000
  pivot: "22B"

sarscov2_2022-23:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2022-07-01"
  max_date: "2023-06-30"
  clade_min_seq: 3000
  pivot: "22E"

sarscov2_2023:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2023-01-01"
  max_date: "2023-12-31"
  clade_min_seq: 3000
  pivot: "23B"

sarscov2_2023-24:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2023-07-01"
  max_date: "2024-06-30"
  clade_min_seq: 3000
  pivot: "24A"

sarscov2_2024:
  local_metadata: "data/sarscov2_subset_metadata.tsv.zst"
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status country
    --filter-query "QC_overall_status != 'bad' & country == 'USA'"
  min_date: "2024-01-01"
  max_date: "2024-12-31"
  clade_min_seq: 3000
  pivot: "24A"

mlr_config: "defaults/mlr-config.yaml"
