# These data options are over-ridden when calling run-mlr-model.py but are expected by MLRConfig
data:
  name: "Test" # Model name
  case_path: "data/test/prepared_cases.tsv"
  seq_path: "data/test/prepared_seq_counts.tsv"

settings:
  fit: true # Fit the model?
  save: true # Save model state?
  load: false # Load old model?
  export_json: true  # Export model results as json
  ps: [0.5] # HPDI intervals to be exported

model:
  generation_time: 4.8
  pivot: "20A"
  hierarchical: true

inference:
  method: "NUTS"
  iters: 50000 # Number of iterations for SVI
  lr: 4e-4 # Learning rate for the model
  num_warmup: 200
  num_samples: 200
