viruses:
  - sarscov2

sarscov2:
  s3_metadata: s3://nextstrain-ncov-private/metadata.tsv.zst
  subset_columns:
    - strain
    - date
    - country
    - clade_nextstrain
    - QC_overall_status
  seq_count_options: >-
    --clade-column clade_nextstrain
    --filter-columns QC_overall_status
    --filter-query "QC_overall_status != 'bad'"
